spring:
  application:
    name: user-service

    #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userdatabase?allowPublicKeyRetrieval=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    #session保存时间（s）
    session:
      timeout: 86400
    # redis配置项
    redis:
      port: 6379
      host: 127.0.0.1
      database: 0


#关闭mybatis-plus自动驼峰命名
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

# swawger文档地址http://127.0.0.1:8080/api/doc.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yijiawen.userSystem

server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost


